// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 26 Dec 2022 22:59:58 PST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "opus/opus.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

